language: generic

sudo: required

services:
  - docker

env:
  - DIST=centos6
  - DIST=fedoradev
  - DIST=ubuntu14
  - DIST=ubuntu14 BSD=true NETWORK=none
  - DIST=tools

before_install:
  - docker build -t bash-completion:$DIST -f test/docker/Dockerfile-$DIST .

script:
  - docker run
    -e CI=true -e DIST=$DIST -e BSD=$BSD -e PYTEST=$PYTEST
    ${NETWORK:+--network $NETWORK}
    -t bash-completion:$DIST test/docker/docker-script.sh
